In [2]:
##Import
import json
import glob
import pandas as pd

## Chargement des fichiers json

In [3]:
# Liste pour stocker les données de tous les fichiers
all_data = []

# Parcourir tous les fichiers correspondants au format rawX.json
for file in sorted(glob.glob("tweet_data/raw*.json")):
    with open(file, "r", encoding="utf-8") as f:
        for line in f:
            try:
                data = json.loads(line.strip())  # Charger chaque ligne JSON
                all_data.append(data)
            except json.JSONDecodeError as e:
                print(f"Erreur de décodage JSON dans {file}: {e}")

# Vérification du nombre de tweets chargés
print(f"Nombre total d'entrées chargées : {len(all_data)}")

Nombre total d'entrées chargées : 401999

## Conversion en dataframe pandas

In [5]:
df = pd.DataFrame(all_data)

In [6]:
display(df)

,created_date,current_time,in_reply_to_status_id_str,in_reply_to_status_id,created_at,in_reply_to_user_id_str,source,retweeted_status,retweet_count,retweeted,...,user,quoted_status,quoted_status_id,quoted_status_permalink,possibly_sensitive,display_text_range,quoted_status_id_str,extended_entities,extended_tweet,withheld_in_countries
0,2018-06-14 04:14:25,1528942465098,None,NaN,Thu Jun 14 02:14:24 +0000 2018,None,"<a href=""http://twitter.com/download/iphone"" r...",{'extended_entities': {'media': [{'display_url...,0,False,...,"{'utc_offset': None, 'friends_count': 826, 'pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-06-14 04:14:25,1528942465150,None,NaN,Thu Jun 14 02:14:24 +0000 2018,None,"<a href=""http://twitter.com/download/iphone"" r...",NaN,0,False,...,"{'utc_offset': None, 'friends_count': 686, 'pr...",{'extended_tweet': {'extended_entities': {'med...,1.007083e+18,{'expanded': 'https://twitter.com/flubase/stat...,False,"[0, 27]",1007083141671026689,NaN,NaN,NaN
2,2018-06-14 04:14:25,1528942465165,None,NaN,Thu Jun 14 02:14:24 +0000 2018,None,"<a href=""http://twitter.com/#!/download/ipad"" ...",{'quoted_status': {'in_reply_to_status_id_str'...,0,False,...,"{'utc_offset': None, 'friends_count': 44, 'pro...","{'in_reply_to_status_id_str': None, 'in_reply_...",1.007082e+18,{'expanded': 'https://twitter.com/ESPNLosAngel...,False,NaN,1007081758389620736,NaN,NaN,NaN
3,2018-06-14 04:14:25,1528942465499,None,NaN,Thu Jun 14 02:14:25 +0000 2018,None,"<a href=""http://twitter.com/download/iphone"" r...",{'extended_tweet': {'extended_entities': {'med...,0,False,...,"{'utc_offset': None, 'friends_count': 3189, 'p...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-06-14 04:14:26,1528942466051,None,NaN,Thu Jun 14 02:14:25 +0000 2018,None,"<a href=""http://twitter.com/download/android"" ...",{'extended_entities': {'media': [{'display_url...,0,False,...,"{'utc_offset': None, 'friends_count': 407, 'pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401994,2018-06-14 12:50:05,1528973405999,None,NaN,Thu Jun 14 10:50:05 +0000 2018,None,"<a href=""https://www.hootsuite.com"" rel=""nofol...",NaN,0,False,...,"{'utc_offset': None, 'friends_count': 63, 'pro...",NaN,NaN,NaN,False,"[0, 140]",NaN,NaN,{'extended_entities': {'media': [{'display_url...,NaN
401995,2018-06-14 12:50:06,1528973406022,None,NaN,Thu Jun 14 10:50:05 +0000 2018,None,"<a href=""http://instagram.com"" rel=""nofollow"">...",NaN,0,False,...,"{'utc_offset': None, 'friends_count': 198, 'pr...",NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN
401996,2018-06-14 12:50:06,1528973406174,None,NaN,Thu Jun 14 10:50:05 +0000 2018,None,"<a href=""http://twitter.com/download/android"" ...","{'in_reply_to_status_id_str': None, 'in_reply_...",0,False,...,"{'utc_offset': None, 'friends_count': 175, 'pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401997,2018-06-14 12:50:06,1528973406201,None,NaN,Thu Jun 14 10:50:05 +0000 2018,None,"<a href=""https://www.hootsuite.com"" rel=""nofol...",NaN,0,False,...,"{'utc_offset': None, 'friends_count': 119, 'pr...",NaN,NaN,NaN,False,"[0, 103]",NaN,{'media': [{'display_url': 'pic.twitter.com/kh...,NaN,NaN
401998,2018-06-14 12:50:06,1528973406227,None,NaN,Thu Jun 14 10:50:05 +0000 2018,None,"<a href=""http://twitter.com/download/iphone"" r...",NaN,0,False,...,"{'utc_offset': None, 'friends_count': 320, 'pr...",NaN,NaN,NaN,False,"[0, 140]",NaN,NaN,{'extended_entities': {'media': [{'display_url...,NaN

## Qualité des données

In [7]:
## Affichage du schema du dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401999 entries, 0 to 401998
Data columns (total 39 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   created_date               401999 non-null  object
 1   current_time               401999 non-null  int64
 2   in_reply_to_status_id_str  7764 non-null    object
 3   in_reply_to_status_id      7764 non-null    float64
 4   created_at                 401999 non-null  object
 5   in_reply_to_user_id_str    10230 non-null   object
 6   source                     401999 non-null  object
 7   retweeted_status           258750 non-null  object
 8   retweet_count              401999 non-null  int64
 9   retweeted                  401999 non-null  bool
 10  geo                        261 non-null     object
 11  filter_level               401999 non-null  object
 12  in_reply_to_screen_name    10230 non-null   object
 13  is_quote_status            401999 non-null  bool
 14  id_str                     401999 non-null  object
 15  in_reply_to_user_id        10230 non-null   float64
 16  favorite_count             401999 non-null  int64
 17  id                         401999 non-null  int64
 18  text                       401999 non-null  object
 19  place                      8883 non-null    object
 20  lang                       401999 non-null  object
 21  quote_count                401999 non-null  int64
 22  favorited                  401999 non-null  bool
 23  coordinates                261 non-null     object
 24  truncated                  401999 non-null  bool
 25  timestamp_ms               401999 non-null  object
 26  reply_count                401999 non-null  int64
 27  entities                   401999 non-null  object
 28  contributors               0 non-null       object
 29  user                       401999 non-null  object
 30  quoted_status              43870 non-null   object
 31  quoted_status_id           43871 non-null   float64
 32  quoted_status_permalink    43870 non-null   object
 33  possibly_sensitive         202845 non-null  object
 34  display_text_range         74666 non-null   object
 35  quoted_status_id_str       43871 non-null   object
 36  extended_entities          106992 non-null  object
 37  extended_tweet             48889 non-null   object
 38  withheld_in_countries      59 non-null      object
dtypes: bool(4), float64(3), int64(6), object(26)
memory usage: 108.9+ MB

In [8]:
## Données manquantes
df.isnull().sum()

created_date                      0
current_time                      0
in_reply_to_status_id_str    394235
in_reply_to_status_id        394235
created_at                        0
in_reply_to_user_id_str      391769
source                            0
retweeted_status             143249
retweet_count                     0
retweeted                         0
geo                          401738
filter_level                      0
in_reply_to_screen_name      391769
is_quote_status                   0
id_str                            0
in_reply_to_user_id          391769
favorite_count                    0
id                                0
text                              0
place                        393116
lang                              0
quote_count                       0
favorited                         0
coordinates                  401738
truncated                         0
timestamp_ms                      0
reply_count                       0
entities                          0
contributors                 401999
user                              0
quoted_status                358129
quoted_status_id             358128
quoted_status_permalink      358129
possibly_sensitive           199154
display_text_range           327333
quoted_status_id_str         358128
extended_entities            295007
extended_tweet               353110
withheld_in_countries        401940
dtype: int64